#!/usr/bin/env bash
set -Eeuo pipefail

readonly SEED_ID="rce-synthea-4-0-0-v1"
readonly TAG_SYSTEM="https://rce-cql.local/fhir/tags/dataset"
readonly TAG_CODE="synthea-4.0.0-v1"
readonly COHORT_TAG_SYSTEM="https://rce-cql.local/fhir/tags/cohort"
readonly TAG_DISPLAY="Synthetic data generated by Synthea 4.0.0"

readonly HAPI_BASE_URL="${HAPI_BASE_URL:-}"
readonly REFERENCE_DATE="${SYNTHEA_REFERENCE_DATE:-20260726}"
readonly CHILD_COUNT="${SYNTHEA_CHILD_COUNT:-6}"
readonly ADOLESCENT_COUNT="${SYNTHEA_ADOLESCENT_COUNT:-4}"
readonly ADULT_COUNT="${SYNTHEA_ADULT_COUNT:-12}"
readonly OLDER_ADULT_COUNT="${SYNTHEA_OLDER_ADULT_COUNT:-8}"

WORK_DIR=""
LOADED_BUNDLES=0
EXPECTED_PATIENTS=0

log() {
  printf '[synthea-seed] %s\n' "$*"
}

dump_java_error_report() {
  local report
  for report in /tmp/rce-synthea-hs-err-*.log /tmp/hs_err_pid*.log /hs_err_pid*.log; do
    [[ -f "${report}" ]] || continue
    printf '\n[synthea-seed] JVM fatal error report: %s\n' "${report}" >&2
    sed -n '1,180p' "${report}" >&2 || true
  done
}

fail() {
  printf '[synthea-seed] ERROR: %s\n' "$*" >&2
  exit 1
}

validate_config() {
  [[ -n "${HAPI_BASE_URL}" ]] || fail 'HAPI_BASE_URL is required'
  [[ "${REFERENCE_DATE}" =~ ^[0-9]{8}$ ]] || fail 'SYNTHEA_REFERENCE_DATE must use YYYYMMDD'

  local value
  for value in "${CHILD_COUNT}" "${ADOLESCENT_COUNT}" "${ADULT_COUNT}" "${OLDER_ADULT_COUNT}"; do
    [[ "${value}" =~ ^[0-9]+$ ]] || fail 'All cohort counts must be non-negative integers'
  done

  EXPECTED_PATIENTS=$((CHILD_COUNT + ADOLESCENT_COUNT + ADULT_COUNT + OLDER_ADULT_COUNT))
  ((EXPECTED_PATIENTS > 0)) || fail 'At least one synthetic patient is required'
}

wait_for_hapi() {
  local attempt
  for attempt in $(seq 1 60); do
    if curl --fail --silent --show-error "${HAPI_BASE_URL}/metadata" >/dev/null; then
      return
    fi
    sleep 2
  done

  fail "HAPI did not become ready at ${HAPI_BASE_URL}"
}

seed_status() {
  local marker
  marker="$(curl --silent --show-error "${HAPI_BASE_URL}/Basic/${SEED_ID}")"

  if [[ "$(jq -r '.resourceType // empty' <<<"${marker}")" != 'Basic' ]]; then
    printf 'missing'
    return
  fi

  jq -r '
    first(
      .extension[]?
      | select(.url == "https://rce-cql.local/fhir/StructureDefinition/seed-status")
      | .valueCode
    ) // "unknown"
  ' <<<"${marker}"
}

put_marker() {
  local status="$1"
  local response_file="${WORK_DIR}/marker-response.json"
  local status_code

  status_code="$(
    jq -n \
      --arg id "${SEED_ID}" \
      --arg tag_system "${TAG_SYSTEM}" \
      --arg tag_code "${TAG_CODE}" \
      --arg tag_display "${TAG_DISPLAY}" \
      --arg status "${status}" \
      --arg reference_date "${REFERENCE_DATE}" \
      --argjson expected "${EXPECTED_PATIENTS}" \
      '{
        resourceType: "Basic",
        id: $id,
        meta: {
          tag: [{system: $tag_system, code: $tag_code, display: $tag_display}]
        },
        code: {
          coding: [{
            system: "https://rce-cql.local/fhir/CodeSystem/seed-dataset",
            code: $tag_code,
            display: $tag_display
          }]
        },
        extension: [
          {
            url: "https://rce-cql.local/fhir/StructureDefinition/seed-status",
            valueCode: $status
          },
          {
            url: "https://rce-cql.local/fhir/StructureDefinition/reference-date",
            valueDate: ($reference_date | strptime("%Y%m%d") | strftime("%Y-%m-%d"))
          },
          {
            url: "https://rce-cql.local/fhir/StructureDefinition/expected-patients",
            valueInteger: $expected
          }
        ]
      }' \
    | curl --silent --show-error \
        --output "${response_file}" \
        --write-out '%{http_code}' \
        --request PUT \
        --header 'Content-Type: application/fhir+json' \
        --data-binary @- \
        "${HAPI_BASE_URL}/Basic/${SEED_ID}"
  )"

  [[ "${status_code}" =~ ^2 ]] || {
    cat "${response_file}" >&2
    fail "HAPI rejected the seed marker with HTTP ${status_code}"
  }
}

generate_cohort() {
  local cohort="$1"
  local count="$2"
  local age_range="$3"
  local population_seed="$4"
  local clinician_seed="$5"
  local output_dir="${WORK_DIR}/${cohort}"

  ((count > 0)) || return
  log "Generating ${count} patients for cohort ${cohort} (${age_range} years)"

  java -jar /opt/synthea.jar \
    -s "${population_seed}" \
    -cs "${clinician_seed}" \
    -r "${REFERENCE_DATE}" \
    -p "${count}" \
    -a "${age_range}" \
    --exporter.baseDirectory="${output_dir}" \
    --exporter.fhir.export=true \
    --exporter.fhir.transaction_bundle=true \
    --exporter.fhir.use_us_core_ig=true \
    --exporter.hospital.fhir.export=true \
    --exporter.practitioner.fhir.export=true \
    --exporter.metadata.export=false \
    --exporter.years_of_history=0 \
    --exporter.pretty_print=false \
    --generate.only_alive_patients=true \
    --generate.append_numbers_to_person_names=true \
    --generate.log_patients.detail=none \
    Massachusetts
}

tag_bundle() {
  local source_file="$1"
  local cohort="${2:-}"
  local tagged_file="$3"

  jq \
    --arg tag_system "${TAG_SYSTEM}" \
    --arg tag_code "${TAG_CODE}" \
    --arg tag_display "${TAG_DISPLAY}" \
    --arg cohort_system "${COHORT_TAG_SYSTEM}" \
    --arg cohort "${cohort}" \
    '
      if .resourceType != "Bundle" then
        error("Expected a FHIR Bundle")
      else
        .type = "transaction"
        | .entry = ((.entry // []) | map(
          if .resource then
            .resource as $resource
            |
            .request = (
              .request // (
                if (($resource.id // "") != "") then
                  {
                    method: "PUT",
                    url: ($resource.resourceType + "/" + $resource.id)
                  }
                else
                  {
                    method: "POST",
                    url: $resource.resourceType
                  }
                end
              )
            )
            |
            .resource.meta = (
              (.resource.meta // {})
              | .tag = (
                  ((.tag // []) + [{
                    system: $tag_system,
                    code: $tag_code,
                    display: $tag_display
                  }])
                  | if $resource.resourceType == "Patient" and $cohort != "" then
                      . + [{system: $cohort_system, code: $cohort}]
                    else
                      .
                    end
                  | unique_by([.system // "", .code // ""])
                )
            )
          else
            .
          end
        ))
      end
    ' "${source_file}" >"${tagged_file}"
}

load_bundle() {
  local source_file="$1"
  local cohort="${2:-}"
  local tagged_file="${WORK_DIR}/tagged-${LOADED_BUNDLES}.json"
  local response_file="${WORK_DIR}/response-${LOADED_BUNDLES}.json"
  local status_code

  tag_bundle "${source_file}" "${cohort}" "${tagged_file}"

  status_code="$(
    curl --silent --show-error \
      --output "${response_file}" \
      --write-out '%{http_code}' \
      --request POST \
      --header 'Content-Type: application/fhir+json' \
      --data-binary "@${tagged_file}" \
      "${HAPI_BASE_URL}"
  )"

  [[ "${status_code}" =~ ^2 ]] || {
    cat "${response_file}" >&2
    fail "HAPI rejected $(basename "${source_file}") with HTTP ${status_code}"
  }

  jq -e '
    .resourceType == "Bundle"
    and (.type == "transaction-response" or .type == "batch-response")
    and all(
      .entry[]?;
      ((.response.status // "") | test("^[23][0-9]{2}"))
    )
  ' "${response_file}" >/dev/null || {
    cat "${response_file}" >&2
    fail "Unexpected transaction response for $(basename "${source_file}")"
  }

  LOADED_BUNDLES=$((LOADED_BUNDLES + 1))
  rm -f "${tagged_file}" "${response_file}"
}

load_reference_bundles() {
  local pattern="$1"
  local label="$2"
  local found=0
  local file

  log "Loading ${label} bundles"
  while IFS= read -r -d '' file; do
    load_bundle "${file}"
    found=$((found + 1))
  done < <(find "${WORK_DIR}" -type f -path '*/fhir/*.json' -iname "${pattern}" -print0)

  ((found > 0)) || fail "Synthea did not create any ${label} bundles"
}

load_patient_bundles() {
  local file
  local cohort
  local found=0

  log 'Loading patient transaction bundles'
  while IFS= read -r -d '' file; do
    cohort="$(basename "$(dirname "$(dirname "${file}")")")"
    load_bundle "${file}" "${cohort}"
    found=$((found + 1))
  done < <(
    find "${WORK_DIR}" -type f -path '*/fhir/*.json' \
      ! -iname 'hospitalinformation*.json' \
      ! -iname 'practitionerinformation*.json' \
      -print0
  )

  [[ "${found}" -eq "${EXPECTED_PATIENTS}" ]] || {
    fail "Expected ${EXPECTED_PATIENTS} patient bundles but found ${found}"
  }
}

patient_count() {
  curl --fail --silent --show-error --get \
    --header 'Accept: application/fhir+json' \
    --data-urlencode "_tag=${TAG_SYSTEM}|${TAG_CODE}" \
    --data-urlencode '_summary=count' \
    "${HAPI_BASE_URL}/Patient" \
  | jq -r '.total // -1'
}

main() {
  trap 'dump_java_error_report' ERR
  validate_config
  WORK_DIR="$(mktemp -d /tmp/rce-synthea.XXXXXX)"
  trap 'rm -rf "${WORK_DIR}"' EXIT

  log 'Java runtime'
  java -version 2>&1 | sed 's/^/[synthea-seed] /'
  log "JAVA_TOOL_OPTIONS=${JAVA_TOOL_OPTIONS:-<unset>}"

  wait_for_hapi

  local status
  status="$(seed_status)"
  case "${status}" in
    completed)
      log "Dataset ${TAG_CODE} is already loaded; nothing to do"
      exit 0
      ;;
    loading)
      fail 'A previous load was interrupted. Reset the local HAPI volume before retrying.'
      ;;
    missing)
      ;;
    *)
      fail "Seed marker has an unsupported status: ${status}"
      ;;
  esac

  generate_cohort children "${CHILD_COUNT}" 0-11 41001 91001
  generate_cohort adolescents "${ADOLESCENT_COUNT}" 12-17 42001 92001
  generate_cohort adults "${ADULT_COUNT}" 18-64 43001 93001
  generate_cohort older-adults "${OLDER_ADULT_COUNT}" 65-90 44001 94001

  put_marker loading
  load_reference_bundles 'hospitalinformation*.json' 'organization/location'
  load_reference_bundles 'practitionerinformation*.json' practitioner
  load_patient_bundles

  local actual_patients
  actual_patients="$(patient_count)"
  [[ "${actual_patients}" -eq "${EXPECTED_PATIENTS}" ]] || {
    fail "Expected ${EXPECTED_PATIENTS} tagged patients in HAPI but found ${actual_patients}"
  }

  put_marker completed
  log "Completed: ${actual_patients} patients and ${LOADED_BUNDLES} transaction bundles loaded"
}

main "$@"
